
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
# Dependabot not working with pnpm so
  # - package-ecosystem: npm
  #   directory: /
  #   schedule:
  #     interval: daily
