version: '3.9'

services:
  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: '${ROOT_PASSWORD}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80

volumes:
  db_data:
