name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    name: 'Build project and run ESLint'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: prisma generate
        run: pnpm exec prisma generate --schema ./prisma/schema.prisma

      - name: Run ESLint
        run: pnpm exec eslint . --max-warnings 0
        continue-on-error: true

      - name: Build
        run: pnpm build

  test:
    name: 'Run the unit tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: prisma generate
        run: pnpm exec prisma generate --schema ./prisma/schema.prisma

      - name: Run tests
        run: pnpm test

  test_e2e:
    name: 'Run the end-to-end tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: prisma generate
        run: pnpm exec prisma generate --schema ./prisma/schema.prisma

      - name: Run tests
        run: pnpm test:e2e
