name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  test_run_install:
    name: 'Test with run_install'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        pnpm:
          - 7.27.0
        os:
          -ubuntu-latest
          -windows-latest
        node-version: [16.x]
        

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: pnpm i

      - name: Run ESLint
        run: pnpm exec eslint . --max-warnings 0
        continue-on-error: true

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test
